### PR TITLE
Please enable Github issues

### PR DESCRIPTION
**Pull request by brylie**
As a community member and developer
I would like to be able to open issues in this repository
So that I may participate in the open development process

### CODE REVIEW

**Comment by paulhendricks** [comment]
I second this request. I too would like to contribute.

**Comment by moezzie** [comment]
+1

**Comment by eugenejo** [comment]
Folks, I will give it a try but please be patient. We're seriously understaffed and I'll be handling pull requests myself for a while.

**Comment by brylie** [comment]
OK, thanks @eugenejo. 

Opening Issues might also make it easier for community members to handle some errors, ideas, etc. ourselves. E.g. we can use an issue to start a discussion and resolve the issue with a PR.

**Comment by wujianbo** [comment]
I just checked update the latest version(Firmware Version DANIEL029), but now I got error steps(no any change, always display 23810 steps. Who can tell me the reason an what should I do for this occasion.

**Comment by eugenejo** [comment]
Hard-reset the device. Press and hold the button for 10 seconds or more
until all LEDs turn on, then release.

On Thursday, May 12, 2016, wujianbo notifications@github.com wrote:

> I just checked update the latest version(Firmware Version DANIEL029), but
> now I got error steps(no any change, always display 23810 steps. Who can
> tell me the reason an what should I do for this occasion.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/AngelSensor/angel-sdk/pull/2#issuecomment-218931522

## 

_With Respect,_

_--Eugene Jorov_
_Co-founder & CTO_
angelsensor.com
https://il.linkedin.com/in/eugenejorov

Investors, join us on 500 Startups Demo Day: http://www.500demoday.co/

---

Follow Angel Sensor:
http://on.fb.me/1RmMU9V  http://bit.ly/1FCHrGA   http://bit.ly/1MjeMrt

**Comment by wujianbo** [comment]
@eugenejo 
I did as you said, but my problem(always displayed 23810 step) can't be resolved, so what should I do next.

**Comment by eugenejo** [comment]
Please forward this information to our customer service at
hello@angelsensor.com. Copy me on your email to expedite things:
eugene.jorov@angelsensor.com.

_With Respect,_

_--Eugene Jorov_
_Co-founder & CTO_
angelsensor.com
https://il.linkedin.com/in/eugenejorov

Investors, join us on 500 Startups Demo Day: http://www.500demoday.co/

---

Follow Angel Sensor:
http://on.fb.me/1RmMU9V  http://bit.ly/1FCHrGA   http://bit.ly/1MjeMrt

**Comment by niqt** [comment]
Hi,
i think the issues feature is foundamental for a opensurce project (otherwise where can i found info about an error?). In my case: the Android and iOS app doesnt' show the BPM is note issue? Only i have it? Is my M1 broken (i received it yesterday)? How CTO/developer i can't wait the response of the support i need speed-up!

**Comment by kparcel** [comment]
@eugenejo 
I also have the problem that the BPM does not appear when using the code for the Android sample app. What changes were made from this version to the version that is available in the Google Play Store?

**Comment by imcpolin** [comment]
Hi,  have you tried long pressing the button? 

When the angel sensor is first shipped out the heart rate is deactivated.  In order to activate it you need to press and hold the button for a couple second,  you should feel it vibrate like crazy.  If the blue led lights turn on at the base of the sensor then the heart rate is active and will take a short while for it to start outputting data. 

Hope this helps ☺️

**Comment by kparcel** [comment]
yes, I have tried that. When I downloaded the app from the Google Play
Store the app worked perfectly fine, but when I took the code for the
Android app off of github and ran that on the same device, the temperature,
steps, and blood oxygen show up fine but the HR does not. When I ran the
github code on my phone it did say that I had to uninstall the "newer
version" of this (the Google Play Store app) in order to run the github
code. This made me think that there was a difference between the two & that
maybe the older version has some sort of a bug dealing with streaming the
HR in it.

Do you know of any way to fix this? Or is it possible to view the current
Angel Sensor App code anywhere?

Thank you,
      Kayci Parcells

**Comment by niqt** [comment]
Hi,
i have a question about the temperature, it's always around 32-33 C°. Is it standard gap (i misure around 36.4 C° with a "normal" thermometer) misusing the temperature on the wrist (otherwise is complicate catch the fever) ?

**Comment by niqt** [comment]
I think is better also to have some instructions as build the sdk

**Comment by brylie** [comment]
Please enable the Issues feature for this repository. There is clearly a community need here.

**Comment by niqt** [comment]
I think i necessary some tool to communicate. i want develop the fall feature, but i don't know if someone workingg on this already. I think it's urgent, we have a lot of communication issue.

**Comment by senshes** [comment]
A device without an active developer community and communication channels is called a brick

**Comment by brylie** [comment]
I would add that the communication channels should be _openly available_, without requiring registration to read the discussion. E.g. a [Discourse forum](https://www.discourse.org/) or Github issue queue. This serves people who want to search for a solution to a common problem, and encourages new community members to join the discussion in progress.

**Comment by brylie** [comment]
# Community tools

The Angel developer and user community need communication tools. A real-time chat solution, such as Slack, is good for quick discussion, but falls short when trying to develop ideas in the long-term.

In order to foster community contribution, planning, and visioning, better community infrastructure is needed.

## Discussion forum

> In their early stages, the most significant concern for projects is likely to be dealing with the inevitable support burden. Handled badly, this might, at best, lead to users turning away and, at worst, might lead to the founder giving up. If success is to be achieved, the leader ultimately has to find people to carry out this work. Employing people is one option; another is encouraging users to help out each other by writing documentation and fixing bugs. However, if this is to happen, there must be an infrastructure in place to allow them to do this.
> - [How to build an open source community - Steering Clear of the Pitfalls](http://oss-watch.ac.uk/resources/howtobuildcommunity#steering-clear-of-the-pitfalls)
> 
> Discussion forums in which participants post and respond to messages are the bread and butter of project communications. 
> - [Producing Open Source Software - Technical Infrastructure - Mailing Lists / Message Forums](http://www.producingoss.com/en/message-forums.html)
> 
> Forums have the advantage of being easy to use. You do not need to be a power user of email to get the most from a forum. One advantage that forums have over mailing lists is providing a searchable archive in the same place as the discussion interface.
> - [Essential tools for running a community-led project - Forum](http://oss-watch.ac.uk/resources/communitytools#tools-for-communication)

## Issue tracker

> By using an issue tracker, you can provide a clear indication to your users as what to expect in future releases of your code. This means that if a user has a specific need for a feature or bug-fix that you have no intention of implementing in the short term, they can opt to invest some of their own resources in adding the feature or fixing the bug.
> - [Essential tools for running a community-led project - Issue tracking](http://oss-watch.ac.uk/resources/communitytools#issue-trackingproject-management)

**Comment by niqt** [comment]
We can create a irc channel

**Comment by brylie** [comment]
@niqt that is a good start. It does duplicate the Slack channel to some degree, and may still be difficult for new community members.

What are your thoughts on hosting a Discourse forum, or some similar discussion platform with email integration?

**Comment by brylie** [comment]
One existing community is the [OpenHealthHub](https://www.openhealthhub.org/). They already have a Discourse forum with email integration.

**Comment by niqt** [comment]
@brylie I think OpenHealthHub is dispersive for our scope (i think we have info only for AngelSensor). I have not idea for forum. I think is important also the @eugenejo thought

**Comment by brylie** [comment]
I opened a discussion thread on OpenHealthHub [regarding the possibility of an open hardware category](https://www.openhealthhub.org/t/open-hardware-category/513). It is just one idea, and worth discussion.

**Comment by niqt** [comment]
@brylie ok, at least it's a start. We can use also Trello for task

**Comment by niqt** [comment]
Waiting for better solutions I created #angelsensor on free node.

**Comment by brylie** [comment]
Thanks @niqt

**Comment by brylie** [comment]
For anyone else who would like to join the channel, there is an [IRC web client](https://webchat.freenode.net/?channels=angelsensor) so you don't need to install any software.

**Comment by brylie** [comment]
I opened a [pull request adding a link to the IRC channel to the README](https://github.com/AngelSensor/angel-sdk/pull/4).

**Comment by niqt** [comment]
Hi,
i would like know which is the goal of Seraphim Sense Ltd. Where is the Community? Where is the news of release and feature? When will we have the SPO2? When new firmware? We don't know nothing, it's bad. I do not want to be argumentative, but there is something wrong!

**Comment by aliasdoc** [comment]
@eugenejo and when we will receive our devices ??? https://www.indiegogo.com/projects/angel-the-first-open-sensor-for-health-and-fitness#/comments

**Comment by niqt** [comment]
I'm implemented the code in the idk for the fall detection but i have this error: "No characteristic 72f442a7-6ecd-4851-8858-403f0a7cab73 in service 68b52738-4a04-40e1-8f83-337a29c3284d" so seems that this feature is not enable in the firmware. When will we have the firmware with it?

**Comment by niqt** [comment]
How  can I push my lua code on the angel (3rd part app) ?

**Comment by quarkcodeOrganization** [comment]
@eugenejo @aliasdoc when we receive our devices?? Or when you close Github account like you did on Twitter... ¿?

**Comment by raspberrypuppies** [comment]
We really need to get some kind of community page up. I'm only commenting here out of desperation. I can't find documentation on the most basic things like "how do you turn it on and off?"
Then it seems basically impossible to connect to it from windows without the BLED112 dongle, which isn't really documented anywhere either. This is really killing me.

**Comment by Flu-Ger** [comment]
The developers take too long to respond and give no explanation on why they don't yet activated issues. As it would be sad to see the community completely go, we decided to create a fork and "organisation" for the community to gather and contribute to.

Everyone is invited to join us at [Community Edition](https://github.com/AngelSensorCommunityEdition/angel-sdk-community).

We do intent to cooperate with the developers when they finally choose to do so.
But until they do, this seems to be our best option...

**Comment by gioppoluca** [comment]
@eugenejo, @yanivmo  I have not received the device.
Can you please answer to mails or deliver?

**Comment by brylie** [comment]
Hi all. We have opened a [support/issue queue on the Angel SDK community edition repository](https://github.com/AngelSensorCommunityEdition/angel-sdk-community/issues). Feel free to open issues there, so we can help this project continue.

**Comment by brylie** [comment]
Closing this pull request

**Pull request closed without merging**
